### ISSUE TITLE
No way to have different u/m on varying items

### ISSUE THREAD

**Issue by Cutelilduck** [Murnto/FactorioData#3]
For example, I have a table with the materials for Science Pack 3 at 45 u/m. Then, I select a different recipe, for example, Flying Robot Frame, and type in 9 u/m. When I click 'Add', my previous entries all also change to 9 u/m, including my Science Pack 3. 

'Add' seems to be applying the u/m value to everything, including past entries. Is this intended or am I missing a function to avoid this?

**Comment by Murnto** [comment]
Should be mitigated in 2ef5b9a / Murnto/factoratio@4bd7474

See new 'Lock speed' toggle in the top right.

Behavior with 'Lock speed' toggled on:
- Already added recipes will keep their current speed
- Newly added recipes will keep the speed from when they are added

Speeds are not automatically refreshed upon toggling off 'Lock speed' to try and prevent accidents.
