### ISSUE TITLE
basic (electronic) circuit board

### ISSUE THREAD

**Issue by nitroorava** [Murnto/FactorioData#6]
the recipes that require basic electronic boards appear as they would require basic circuit boards instead. All but two of the recipes that need basic electronic boards (the blue wires on the board) appear to need the basic circuit boards (the orange wires on the board). Can this be fixed please =)

**Comment by Murnto** [comment]
Which mod pack(s) does this occur in? This is hopefully just a case of the pack info being outdated.

**Comment by nitroorava** [comment]
No the fault is not in the game, it's on the factorio data page.
20.6.2016 7.38 "David" notifications@github.com kirjoitti:

**Comment by Murnto** [comment]
Yes, the mods used to generate the pack info for FactorioData are likely out of date.

**Comment by Murnto** [comment]
I've updated the pack data for the bobmods-f12 pack. Please let me know if the issue is fixed.

**Comment by nitroorava** [comment]
Ahh f12 :) I've been using the f11.
Yep it seems to be correct on the f12 pack. Thank you!

I've updated the pack data for the bobmods-f12 pack. Please let me know if
the issue is fixed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Murnto/FactorioData/issues/6#issuecomment-227338234,
or mute the thread
https://github.com/notifications/unsubscribe/ATGlinl0GDv4IhFpfSmfb3KtTg-lH1cLks5qN2m5gaJpZM4I5Onx
.
