### ISSUE TITLE
No support for F13

### ISSUE THREAD

**Issue by DRY411S** [Murnto/FactorioData#7]
Are there plans to add support for F13?

For example, there are no curved rails in F13, and 2 new types of inserter.

**Comment by Murnto** [comment]
ff8f78e allows F13 data to be loaded, however a small number of routes/items are broken. 

The rails item for example, linked from [/pack/base-f13/tech/railway](http://factorio.rotol.me/pack/base-f13/tech/railway) doesn't connect to [/pack/base-f13/i/item/rail](http://factorio.rotol.me/pack/base-f13/i/item/rail), I haven't had time to look into the cause of this yet.
