### ISSUE TITLE
"Unexpected token" error on pages

### ISSUE THREAD

**Issue by solntcev** [Murnto/FactorioData#8]
Hello,

I generated pack from factorio 0.13.13 and try to use it with latest FactorioData.

I get "iron" filter on start page, but errors on other pages:

/pack/base-pack/i/item/iron-ore -> "Unexpected token (1:138)"
/pack/base-pack/tech -> "Unexpected token (1:87)"
/pack/base-pack/itemcats -> "Unexpected token (1:77)"
/pack/ -> "Unexpected token (1:68)"

How can I troubleshoot this issue?

same error with packs from PackData repo.
/pack/base-f11/tech -> "Unexpected token (1:87)"

What nodejs version is required for this app?

**Comment by Murnto** [comment]
What OS and Nodejs version are you running?
Nodejs versions v6.3.1, v5.1.0 and v4.4.7 on Linux work fine locally.

(Unrelated) Factorio-PackGen is currently ahead of FactorioData by a commit, however this only results in malformed mod lists on /pack/.

**Comment by solntcev** [comment]
CentOS 6 / Node v0.10.13
I tried to run this on virtual hosting server.

Will try to launch it on other server later.

**Comment by Murnto** [comment]
Node v0.10.13 is quite old (2013), [Node Version Manager](https://github.com/creationix/nvm) may be of use obtaining a more recent version.

**Comment by Murnto** [comment]
Feel free to reopen this if you continue to have issues.

**Comment by solntcev** [comment]
Yes, looks like old node version caused issues.
I tried it on 4.4 and it worked.
