### ISSUE TITLE
Support for 0.14?

### ISSUE THREAD

**Issue by Karosieben** [Murnto/FactorioData#9]
Any plans to support 0.14 correctly?
I've tried to generate packdata myself for bobsmods 0.14 and for example the "invar-alloy" gives me an "Cannot read property 'type' of undefined"-error.

May i help you anywhere?

Greetings from Germany,
Karosieben

**Comment by Murnto** [comment]
This project is deprecated in favor of https://github.com/Murnto/FactorioData-dlang. 

Murnto/FactorioData-dlang@848ae16 and Murnto/FactorioData-dlang@1f894aa fix all bugs I've noticed in relation to 0.14 however.
